import { Lato } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./contexts/AuthContext";
import Header  from "./components/Header";

const inter = Lato({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Donkey Betz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className={inter.className}>
        <Header />
        {children}
        </body>
      </AuthProvider>
    </html>
  );
}
