"""Added custom_id to EmbeddingStore

Revision ID: ca8b2100be02
Revises: 4c28c5c488d7
Create Date: 2024-04-09 14:44:11.741864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8b2100be02'
down_revision = '4c28c5c488d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('langchain_pg_embedding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('langchain_pg_embedding', schema=None) as batch_op:
        batch_op.drop_column('custom_id')

    # ### end Alembic commands ###
