"""Added audio, image and prompt to chatmessage.

Revision ID: ed378d8a0bcb
Revises: 63a5eb0a9830
Create Date: 2024-05-15 12:41:46.379773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed378d8a0bcb'
down_revision = '63a5eb0a9830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('prompt', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('prompt')
        batch_op.drop_column('image_url')
        batch_op.drop_column('audio_url')

    # ### end Alembic commands ###
